//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppService.Servicio {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioSoap", Namespace="http://tempuri.org/")]
    public partial class Servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InfoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccederOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductoShowOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtIdOperationCompleted;
        
        /// CodeRemarks
        public Servicio() {
            this.Url = "http://192.168.1.66:90/Servicio.asmx";
        }
        
        public Servicio(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// CodeRemarks
        public event registrarUsuarioCompletedEventHandler registrarUsuarioCompleted;
        
        /// CodeRemarks
        public event InfoUsuarioCompletedEventHandler InfoUsuarioCompleted;
        
        /// CodeRemarks
        public event AccederCompletedEventHandler AccederCompleted;
        
        /// CodeRemarks
        public event ProductoShowCompletedEventHandler ProductoShowCompleted;
        
        /// CodeRemarks
        public event ActualizarDaldoCompletedEventHandler ActualizarDaldoCompleted;
        
        /// CodeRemarks
        public event ObtIdCompletedEventHandler ObtIdCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// CodeRemarks
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string registrarUsuario(string Nombre, string Apellidos, string Correo, string Contra) {
            object[] results = this.Invoke("registrarUsuario", new object[] {
                        Nombre,
                        Apellidos,
                        Correo,
                        Contra});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void registrarUsuarioAsync(string Nombre, string Apellidos, string Correo, string Contra) {
            this.registrarUsuarioAsync(Nombre, Apellidos, Correo, Contra, null);
        }
        
        /// CodeRemarks
        public void registrarUsuarioAsync(string Nombre, string Apellidos, string Correo, string Contra, object userState) {
            if ((this.registrarUsuarioOperationCompleted == null)) {
                this.registrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("registrarUsuario", new object[] {
                        Nombre,
                        Apellidos,
                        Correo,
                        Contra}, this.registrarUsuarioOperationCompleted, userState);
        }
        
        private void OnregistrarUsuarioOperationCompleted(object arg) {
            if ((this.registrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarUsuarioCompleted(this, new registrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InfoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet InfoUsuario(string Correo, string password) {
            object[] results = this.Invoke("InfoUsuario", new object[] {
                        Correo,
                        password});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// CodeRemarks
        public void InfoUsuarioAsync(string Correo, string password) {
            this.InfoUsuarioAsync(Correo, password, null);
        }
        
        /// CodeRemarks
        public void InfoUsuarioAsync(string Correo, string password, object userState) {
            if ((this.InfoUsuarioOperationCompleted == null)) {
                this.InfoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInfoUsuarioOperationCompleted);
            }
            this.InvokeAsync("InfoUsuario", new object[] {
                        Correo,
                        password}, this.InfoUsuarioOperationCompleted, userState);
        }
        
        private void OnInfoUsuarioOperationCompleted(object arg) {
            if ((this.InfoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InfoUsuarioCompleted(this, new InfoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Acceder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Acceder(string Correo, string Password) {
            object[] results = this.Invoke("Acceder", new object[] {
                        Correo,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void AccederAsync(string Correo, string Password) {
            this.AccederAsync(Correo, Password, null);
        }
        
        /// CodeRemarks
        public void AccederAsync(string Correo, string Password, object userState) {
            if ((this.AccederOperationCompleted == null)) {
                this.AccederOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccederOperationCompleted);
            }
            this.InvokeAsync("Acceder", new object[] {
                        Correo,
                        Password}, this.AccederOperationCompleted, userState);
        }
        
        private void OnAccederOperationCompleted(object arg) {
            if ((this.AccederCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccederCompleted(this, new AccederCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProductoShow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProductoShow() {
            object[] results = this.Invoke("ProductoShow", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// CodeRemarks
        public void ProductoShowAsync() {
            this.ProductoShowAsync(null);
        }
        
        /// CodeRemarks
        public void ProductoShowAsync(object userState) {
            if ((this.ProductoShowOperationCompleted == null)) {
                this.ProductoShowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductoShowOperationCompleted);
            }
            this.InvokeAsync("ProductoShow", new object[0], this.ProductoShowOperationCompleted, userState);
        }
        
        private void OnProductoShowOperationCompleted(object arg) {
            if ((this.ProductoShowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductoShowCompleted(this, new ProductoShowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarDaldo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarDaldo(string correo, string pass, double saldo) {
            object[] results = this.Invoke("ActualizarDaldo", new object[] {
                        correo,
                        pass,
                        saldo});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void ActualizarDaldoAsync(string correo, string pass, double saldo) {
            this.ActualizarDaldoAsync(correo, pass, saldo, null);
        }
        
        /// CodeRemarks
        public void ActualizarDaldoAsync(string correo, string pass, double saldo, object userState) {
            if ((this.ActualizarDaldoOperationCompleted == null)) {
                this.ActualizarDaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDaldoOperationCompleted);
            }
            this.InvokeAsync("ActualizarDaldo", new object[] {
                        correo,
                        pass,
                        saldo}, this.ActualizarDaldoOperationCompleted, userState);
        }
        
        private void OnActualizarDaldoOperationCompleted(object arg) {
            if ((this.ActualizarDaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDaldoCompleted(this, new ActualizarDaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ObtId() {
            object[] results = this.Invoke("ObtId", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void ObtIdAsync() {
            this.ObtIdAsync(null);
        }
        
        /// CodeRemarks
        public void ObtIdAsync(object userState) {
            if ((this.ObtIdOperationCompleted == null)) {
                this.ObtIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtIdOperationCompleted);
            }
            this.InvokeAsync("ObtId", new object[0], this.ObtIdOperationCompleted, userState);
        }
        
        private void OnObtIdOperationCompleted(object arg) {
            if ((this.ObtIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtIdCompleted(this, new ObtIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void registrarUsuarioCompletedEventHandler(object sender, registrarUsuarioCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void InfoUsuarioCompletedEventHandler(object sender, InfoUsuarioCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InfoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InfoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void AccederCompletedEventHandler(object sender, AccederCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccederCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccederCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void ProductoShowCompletedEventHandler(object sender, ProductoShowCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductoShowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductoShowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void ActualizarDaldoCompletedEventHandler(object sender, ActualizarDaldoCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    public delegate void ObtIdCompletedEventHandler(object sender, ObtIdCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.1.5.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
